id = "gdsl"
name = "GDSL"
version = "0.0.1"
schema_version = 1
authors = ["Parantapa Bhattacharya <parantapa@virginia.edu>"]
description = "GDSL support for Zed editor"
repository = "https://github.com/NSSAC/gdsl-zed-extension"

[grammars.gdsl]
repository = "https://github.com/NSSAC/tree-sitter-gdsl"
commit = "d2a6feffbd885cdbe66824e408af9a6b35c7b21b"
